### ISSUE TITLE
Jupyter compatibility

### ISSUE THREAD

**Issue by HelloWorldManiac** [KevinFasusi/supplychainpy#47]
On trying to import a block 'analyse' from 'supplychainpy.model_inventory ' an error occurs:

'  File "C:\Users\User\Anaconda2\lib\site-packages\supplychainpy-0.0.4-py2.7-win-amd64.egg\supplychainpy\model_inventory.py", line 54
    def analyse(currency: str, z_value: Decimal = 1.28, reorder_cost: Decimal = 10, interval_length: int = 12,
                        ^
SyntaxError: invalid syntax'

The code is not typical for Python
How could this problem be fixed?

**Comment by KevinFasusi** [comment]
Hi HelloWorld Maniac,

From the error message it looks like your are using Python 2.7. Is that correct?  The library works with python >=3.5. Since it looks like you are using Anaconda, please create a new environment:

`$ conda create -n <name-env> python=3.5`

`$ pip install supplychainpy`

If you are using the reporting feature you will  also need to install `textblob`:

`$ pip install textblob`

`$pyton -m textblob.download_corpora`
